### ISSUE TITLE
Alias for Official Email Address

### ISSUE THREAD

**Issue by fedpy** [fedpy/DraganTalamh#13]
Must create an official email address for the project. 

What alias would make most sense for the general, official related activities?
- info@dragantalamh.ie
- hello@dragantalamh.ie
- hi@dragantalamh.ie

Thanks guys!

**Comment by GintsGavars** [comment]
info me thinks sounds most official of these

**Comment by fedpy** [comment]
Perfect, thank you Gints for your opinion. info@dragantalamh.ie it is!

**Comment by Mark-Barry** [comment]
I'd say info as well.

**Comment by aindriu18** [comment]
Yea happy enough with info. Sorry I didn't reply sooner
