### ISSUE TITLE
Project not compatible with .Net Core

### ISSUE THREAD

**Issue by moreirayokoyama** [fedpy/DraganTalamh#17]
If we use .Net Core instead of .Net Framework, Linux and Mac users would be able to contribute.

We may benefit from a wider community with a simple change.

**Comment by fedpy** [comment]
Hi Daniel,

Thank you for your concerns. We have collectively decided that the .Net Framework is the most appropriate choice for this project. As a Linux user, I have tested .Net Framework compatibility with a few Linux distributions and can confirm that there are no issues with .Net Framework on Linux. I have tested the current project solution using Fedora, Slackware and Ubuntu on [MonoDevelop](https://www.monodevelop.com/) as well as [ReSharper](https://www.jetbrains.com/resharper/) IDE's. Unfortunately I can't speak for the Mac users as I don't know one or have access to their working environment. However, should the Mac users experience any issues with .Net Framework their best option is to deploy a Windows or Linux based Virtual Machine.

**Comment by moreirayokoyama** [comment]
I see. But now I'm curious. How is it more appropriate?

**Comment by moreirayokoyama** [comment]
Maybe I rushing things a bit too much. I'll wait for more information about the project before making new questions.

**Comment by fedpy** [comment]
Apologies for confusion Daniel. It means that it is appropriate to us i.e. this is what we have learned so far and are familiar with. There are of course other ways, libraries, languages, methods, etc. to achieve the same goal. However, we have decided to use .Net Framework for now. Thank you!
