### ISSUE TITLE
Refactor and update panel names

### ISSUE THREAD

**Issue by fedpy** [fedpy/DraganTalamh#21]
Hi GUI Masters!

Can we update the diagram and refactor the source code to reflect the following changes:
- MainPanel to RightPanel
- SidebarPanel to LeftPanel

So that the new design and source code should read:
- LeftPanel
- RightPanel
- BottomPanel

Thank you!

**Comment by RalsD** [comment]
Sorry, chief! Still new to Git - pushed the changes to development - both for the panels and MainForm TODO list.

**Comment by fedpy** [comment]
Hi @RalsD, that's absolutely fantastic work! Did you get a chance to update UML Diagram?

Also, if the items from the TODO list no longer apply, you can remove them ;)

Thank you so much!

**Comment by RalsD** [comment]
Ok, no worries! Will do!

**Comment by fedpy** [comment]
Thanks so much for all your help!
